#!/bin/sh

# Compute env vars to use in a 'docker run' command
# to bootstrap a consul cluster using etcd.
#
# Based on two gists:
#
# https://gist.github.com/yaronr/aa5e9d1871f047568c84
# https://gist.github.com/philips/56fa3f5dae9060fbd100
#
# and progrium's start script from progrium/consul

bridge_ip="$(ip route | awk '/^default/{print $3}')"
private_ip=$COREOS_PRIVATE_IPV4
etcd_root="http://$bridge_ip:4001/v2"
echo "bridge_ip =" $bridge_ip
echo "private_ip =" $private_ip
echo "etcd_root =" $etcd_root

# Atomically determine if we're the first to bootstrap
curl -L --fail $etcd_root/keys/consul.io/bootstrap/bootstrapped?prevExist=false -XPUT -d value=$private_ip >/dev/null 2>&1
if [ $? != 0 ]; then
  # Another node won the race, assume joining with the rest.
  echo "Not first machine, joining others..."

  export first=""
  while [ "$first" == "" ]; do
    echo "Reading IP of bootstrap node..."
    export first="$(curl -L --fail $etcd_root/keys/consul.io/bootstrap/bootstrapped 2>/dev/null | jq '.node.value' | tr -d '\"')"
    sleep 5
  done
  echo "first =" $first

  others=$(curl -L --fail $etcd_root/keys/consul.io/bootstrap/machines/ 2>/dev/null | jq '.node.nodes[].key' | while read line; do
          ip=$(curl -L --fail $etcd_root/keys/${line} 2>/dev/null | jq '.node.value' | tr -d '\"')
          if [[ "${ip}" != "" && "${ip}" != "${first}" ]]; then
            echo -n "-retry-join ${ip} "
          fi
        done)

  flags="-retry-join $first $others"
  bootstrap=""
else
  # We're the first to bootstrap.
  echo "First machine, setting consul bootstrap flag..."
  flags=""
  bootstrap="-bootstrap"
fi

echo "Flags are:" $flags
echo "Bootstrap is:" $bootstrap

if [ "$1" == "--server" ]; then
  curl -L --fail $etcd_root/keys/consul.io/bootstrap/machines/$HOSTNAME -XPUT -d value=$private_ip >/dev/null 2>&1
  if [ "$?" != 0 ]; then
    echo "Failed to write IP $private_ip for $HOSTNAME to etcd"
  fi
fi

echo "Writing environment.consul..."
cat > /etc/env.d/environment.consul <<EOF
CONSUL_PORTS="-p $private_ip:8300:8300 \
-p $private_ip:8301:8301 \
-p $private_ip:8301:8301/udp \
-p $private_ip:8302:8302 \
-p $private_ip:8302:8302/udp \
-p $private_ip:8400:8400 \
-p $private_ip:8500:8500 \
-p $bridge_ip:53:53/udp"
CONSUL_BOOTSTRAP="${bootstrap}"
CONSUL_JOIN="${flags}"
EOF
