#!/bin/sh

# Compute env vars to use in a 'docker run' command
# to bootstrap a RethinkDB cluster using etcd.
#
# Based on two gists:
#
# https://gist.github.com/yaronr/aa5e9d1871f047568c84
# https://gist.github.com/philips/56fa3f5dae9060fbd100
#
# and progrium's start script from progrium/consul

bridge_ip="$(ip route | awk '/^default/{print $3}')"
private_ip=$COREOS_PRIVATE_IPV4
etcd_root="http://$bridge_ip:4001/v2"
echo "bridge_ip =" $bridge_ip
echo "private_ip =" $private_ip
echo "etcd_root =" $etcd_root

# Atomically determine if we're the first to bootstrap
curl -L --fail $etcd_root/keys/rethinkdb.com/bootstrap/bootstrapped?prevExist=false -XPUT -d value=$private_ip >/dev/null 2>&1
if [ $? != 0 ]; then
  # Another node won the race, assume joining with the rest.
  echo "Not first machine, joining others..."

  export first=""
  while [ "$first" == "" ]; do
    echo "Reading IP of bootstrap node..."
    export first="$(curl -L --fail $etcd_root/keys/rethinkdb.com/bootstrap/bootstrapped?quorum=true 2>/dev/null | jq '.node.value' | tr -d '\"')"
  done
  echo "first =" $first

  others=$(curl -L --fail $etcd_root/keys/rethinkdb.com/bootstrap/machines/?quorum=true 2>/dev/null | jq '.node.nodes[].key' | while read line; do
          ip=$(curl -L --fail $etcd_root/keys/${line}?quorum=true 2>/dev/null | jq '.node.value' | tr -d '\"')
          if [[ "${ip}" != "" && "${ip}" != "${first}" ]]; then
            echo -n "--join ${ip} "
          fi
        done)

  joins="--join $first $others"
else
  # We're the first to bootstrap.
  echo "First machine, setting rethinkdb bootstrap flag..."
  joins=""
fi

echo "Joins are:" $joins

if [ "$1" == "--server" ]; then
  curl -L --fail $etcd_root/keys/rethinkdb.com/bootstrap/machines/$HOSTNAME -XPUT -d value=$private_ip >/dev/null 2>&1
  if [ "$?" != 0 ]; then
    echo "Failed to write IP $private_ip for $HOSTNAME to etcd"
  fi
fi

echo "Writing environment.rethinkdb"
cat > /etc/env.d/environment.rethinkdb <<EOF
RETHINKDB_PORTS="-p $private_ip:28015:28015 \
-p $private_ip:29015:29015 \
-p $private_ip:8080:8080"
RETHINKDB_JOIN="${joins}"
EOF
